ac_dim: 6
actor_update_frequency: 1
critic_target_update_frequency: 1
discrete: false
gamma: 0.99
init_temperature: 0.1
learning_rate: 0.0003
n_layers: 2
num_actor_updates_per_agent_update: 1
num_agent_train_steps_per_iter: 1
num_critic_updates_per_agent_update: 1
ob_dim: 17
size: 256
