mbpo_stationary_env:
    sac_train_batch_size: 1024
    sac_discount: 0.98
    lr: 0.0035116930726531597
    sac_n_layers: 2
    sac_size: 256
    size: 100
    train_batch_size: 1024
    mpc_horizon: 11.658230923329675
    ensemble_size: 3
    learning_rate: 0.03395702200616835
    batch_size_initial: 5000
    mpc_num_action_sequences: 100
    cem_alpha: 0.01
    num_agent_train_steps_per_iter: 1000

mbpo_config:
    add_sl_noise: true
    batch_size: 768
    batch_size_initial: 3072
    cem_alpha: 1
    cem_iterations: 4
    cem_num_elites: 5
    ensemble_size: 3
    env_name: FishStationary-v0
    ep_len: 1000
    eval_batch_size: 400
    exp_name: q6_fS_small
    learning_rate: 0.001
    logdir: None
    mbpo_rollout_length: 0
    mpc_action_sampling_strategy: random
    mpc_horizon: 10
    mpc_num_action_sequences: 1000
    n_iter: 10
    n_layers: 2
    no_gpu: false
    num_agent_train_steps_per_iter: 1000
    sac_actor_update_frequency: 1
    sac_batch_size: 2000
    sac_critic_target_update_frequency: 1
    sac_discount: 0.999
    sac_init_temperature: 0.1
    sac_learning_rate: 0.004
    sac_n_iter: 5000
    sac_n_layers: 2
    sac_num_actor_updates_per_agent_update: 1
    sac_num_agent_train_steps_per_iter: 1
    sac_num_critic_updates_per_agent_update: 1
    sac_size: 256
    sac_train_batch_size: 256
    save_params: false
    scalar_log_freq: 1
    seed: 1
    size: 250
    train_batch_size: 512
    video_log_freq: -1
    which_gpu: 0
    eval_eps: 1